hogarBal = psf2otf(latent_tensor, [15,15])
# print(hogarBal)
# putkirBal = otf2psf(hogarBal, [10,10])
# print(torch.abs(putkirBal))
# # haha = ifft2(hogarBal)
# x = torch.tensor([[1,-1]])
# y = psf2otf(x, [5,5])
# print(y)
# z = otf2psf(y,[1,2])
# print(z)